/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnMenuRegistroLibro = new javax.swing.JButton();
        btnMenuCarnet = new javax.swing.JButton();
        btnMenuMulta = new javax.swing.JButton();
        btnMenuVerificarLibro = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnVerPrestamos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administrador");

        btnMenuRegistroLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuRegistroLibro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuRegistroLibro.setText("Registrar Libros");
        btnMenuRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistroLibroActionPerformed(evt);
            }
        });

        btnMenuCarnet.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuCarnet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuCarnet.setText("Carnet");
        btnMenuCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCarnetActionPerformed(evt);
            }
        });

        btnMenuMulta.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuMulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuMulta.setText("Añadir multas");
        btnMenuMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMultaActionPerformed(evt);
            }
        });

        btnMenuVerificarLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuVerificarLibro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuVerificarLibro.setText("Verificar ejemplares");
        btnMenuVerificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuVerificarLibroActionPerformed(evt);
            }
        });

        btnRegreso.setText("Atras");

        btnVerPrestamos.setBackground(new java.awt.Color(0, 102, 102));
        btnVerPrestamos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerPrestamos.setText("Ver prestamos");
        btnVerPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenuVerificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnVerPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnRegreso)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnRegreso)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnMenuRegistroLibro)
                .addGap(18, 18, 18)
                .addComponent(btnMenuCarnet)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMulta)
                .addGap(18, 18, 18)
                .addComponent(btnMenuVerificarLibro)
                .addGap(18, 18, 18)
                .addComponent(btnVerPrestamos)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistroLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegistroLibroActionPerformed

    private void btnMenuCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuCarnetActionPerformed

    private void btnMenuMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuMultaActionPerformed

    private void btnMenuVerificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuVerificarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuVerificarLibroActionPerformed

    private void btnVerPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMenuCarnet;
    public javax.swing.JButton btnMenuMulta;
    public javax.swing.JButton btnMenuRegistroLibro;
    public javax.swing.JButton btnMenuVerificarLibro;
    public javax.swing.JButton btnRegreso;
    public javax.swing.JButton btnVerPrestamos;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
