/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class VentanaRegistroAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public VentanaRegistroAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EdadAdmin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IdInicioSesionAdmin = new javax.swing.JTextField();
        btnRgistroAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NombreAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ApellidoAdmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DniAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CorreoAdmin = new javax.swing.JTextField();
        TelefonoAdmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnInicioAdmin1 = new javax.swing.JButton();
        btnVolverventanalogin = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel5.setText("jLabel5");

        jLabel11.setText("jLabel11");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Edad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        EdadAdmin.setBackground(new java.awt.Color(255, 255, 255));
        EdadAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadAdminActionPerformed(evt);
            }
        });
        jPanel2.add(EdadAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Inicio de Sesion");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 407, -1, -1));

        IdInicioSesionAdmin.setBackground(new java.awt.Color(255, 255, 255));
        IdInicioSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInicioSesionAdminActionPerformed(evt);
            }
        });
        jPanel2.add(IdInicioSesionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 411, 325, -1));

        btnRgistroAdmin.setBackground(new java.awt.Color(0, 102, 102));
        btnRgistroAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRgistroAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnRgistroAdmin.setText("Registrar");
        btnRgistroAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRgistroAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnRgistroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombres:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        NombreAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(NombreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellidos:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        ApellidoAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ApellidoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        DniAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(DniAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Correo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        CorreoAdmin.setBackground(new java.awt.Color(255, 255, 255));
        CorreoAdmin.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(CorreoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 270, -1));

        TelefonoAdmin.setBackground(new java.awt.Color(255, 255, 255));
        TelefonoAdmin.setForeground(new java.awt.Color(153, 153, 153));
        TelefonoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoAdminActionPerformed(evt);
            }
        });
        jPanel2.add(TelefonoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 270, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de Administrador");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("O");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        btnInicioAdmin1.setBackground(new java.awt.Color(0, 102, 102));
        btnInicioAdmin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicioAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioAdmin1.setText("Inicio sesion");
        btnInicioAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAdmin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicioAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        btnVolverventanalogin.setBackground(new java.awt.Color(0, 102, 102));
        btnVolverventanalogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverventanalogin.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverventanalogin.setText("Volver");
        btnVolverventanalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverventanaloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverventanalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelefonoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoAdminActionPerformed

    private void IdInicioSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInicioSesionAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInicioSesionAdminActionPerformed

    private void EdadAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadAdminActionPerformed

    private void btnRgistroAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRgistroAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRgistroAdminActionPerformed

    private void btnInicioAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioAdmin1ActionPerformed

    private void btnVolverventanaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverventanaloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverventanaloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ApellidoAdmin;
    public javax.swing.JTextField CorreoAdmin;
    public javax.swing.JTextField DniAdmin;
    public javax.swing.JTextField EdadAdmin;
    public javax.swing.JTextField IdInicioSesionAdmin;
    public javax.swing.JTextField NombreAdmin;
    public javax.swing.JTextField TelefonoAdmin;
    public javax.swing.JButton btnInicioAdmin1;
    public javax.swing.JButton btnRgistroAdmin;
    public javax.swing.JButton btnVolverventanalogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
