/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class VentanaRegistroLibros extends javax.swing.JFrame {

    /**
     * Creates new form Ventana3
     */
    public VentanaRegistroLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAñadirLibro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnVerificarLibroEjemplar = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnActualizartabla = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnModificarLibro = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAñadirLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnAñadirLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadirLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirLibro.setText("Añadir Libro");
        btnAñadirLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirLibroActionPerformed(evt);
            }
        });

        TablaLibros.setBackground(new java.awt.Color(204, 204, 204));
        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaLibros);
        if (TablaLibros.getColumnModel().getColumnCount() > 0) {
            TablaLibros.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            TablaLibros.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            TablaLibros.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            TablaLibros.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registro y visualizacion de Libros");

        btnVerificarLibroEjemplar.setBackground(new java.awt.Color(0, 102, 102));
        btnVerificarLibroEjemplar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerificarLibroEjemplar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificarLibroEjemplar.setText("Verificar Ejemplares");
        btnVerificarLibroEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarLibroEjemplarActionPerformed(evt);
            }
        });

        btnRegreso.setBackground(new java.awt.Color(0, 102, 102));
        btnRegreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegreso.setForeground(new java.awt.Color(255, 255, 255));
        btnRegreso.setText("Atras");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        btnActualizartabla.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizartabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizartabla.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizartabla.setText("Actualizar tabla");
        btnActualizartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizartablaActionPerformed(evt);
            }
        });

        btnEliminarLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminarLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarLibro.setText("Elminiar Libro");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        btnModificarLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnModificarLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarLibro.setText("Modificar Libro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRegreso)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAñadirLibro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVerificarLibroEjemplar)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnActualizartabla)
                                        .addGap(87, 87, 87))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnEliminarLibro)
                        .addGap(63, 63, 63)
                        .addComponent(btnModificarLibro)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegreso))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirLibro)
                    .addComponent(btnVerificarLibroEjemplar)
                    .addComponent(btnActualizartabla))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarLibro)
                    .addComponent(btnModificarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoAdminActionPerformed

    private void btnAñadirLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirLibroActionPerformed

    private void btnVerificarLibroEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarLibroEjemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarLibroEjemplarActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnActualizartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizartablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizartablaActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaLibros;
    public javax.swing.JButton btnActualizartabla;
    public javax.swing.JButton btnAñadirLibro;
    public javax.swing.JButton btnEliminarLibro;
    public javax.swing.JButton btnModificarLibro;
    public javax.swing.JButton btnRegreso;
    public javax.swing.JButton btnVerificarLibroEjemplar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
