/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class VentanaAdminCarnet extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    public VentanaAdminCarnet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAñadirCarnet = new javax.swing.JButton();
        btnCambiarEstadoCarnet = new javax.swing.JButton();
        btnregresoInicio = new javax.swing.JButton();
        btnActualizarTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCarnet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carnets de Usuarios");

        btnAñadirCarnet.setBackground(new java.awt.Color(0, 102, 102));
        btnAñadirCarnet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadirCarnet.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirCarnet.setText("Añadir Carnet");
        btnAñadirCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCarnetActionPerformed(evt);
            }
        });

        btnCambiarEstadoCarnet.setBackground(new java.awt.Color(0, 102, 102));
        btnCambiarEstadoCarnet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiarEstadoCarnet.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarEstadoCarnet.setText("Cambiar estado de Carnet");
        btnCambiarEstadoCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoCarnetActionPerformed(evt);
            }
        });

        btnregresoInicio.setBackground(new java.awt.Color(0, 51, 51));
        btnregresoInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresoInicio.setText("Atras");
        btnregresoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoInicioActionPerformed(evt);
            }
        });

        btnActualizarTabla.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizarTabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarTabla.setText("Actualizar Tabla");
        btnActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaActionPerformed(evt);
            }
        });

        TablaCarnet.setBackground(new java.awt.Color(204, 204, 204));
        TablaCarnet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaCarnet);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnAñadirCarnet)
                        .addGap(41, 41, 41)
                        .addComponent(btnCambiarEstadoCarnet)
                        .addGap(53, 53, 53)
                        .addComponent(btnActualizarTabla))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnregresoInicio)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnregresoInicio))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarEstadoCarnet)
                    .addComponent(btnAñadirCarnet)
                    .addComponent(btnActualizarTabla))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresoInicioActionPerformed

    private void btnAñadirCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirCarnetActionPerformed

    private void btnCambiarEstadoCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarEstadoCarnetActionPerformed

    private void btnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaCarnet;
    public javax.swing.JButton btnActualizarTabla;
    public javax.swing.JButton btnAñadirCarnet;
    public javax.swing.JButton btnCambiarEstadoCarnet;
    public javax.swing.JButton btnregresoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
