/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class VentanaPrestamoLibro extends javax.swing.JFrame {

    /**
     * Creates new form Ventana9
     */
    public VentanaPrestamoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnregresoInicio = new javax.swing.JButton();
        btnMenuRegistroAdmin = new javax.swing.JButton();
        btnMenuRegistroLibro = new javax.swing.JButton();
        btnMenuCarnet = new javax.swing.JButton();
        btnMenuMulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnConsultarLibro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NombreLibroPrestamo = new javax.swing.JTextField();
        btnPrestamoLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EjemplarLibroPrestamo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnregresoInicio.setBackground(new java.awt.Color(0, 51, 51));
        btnregresoInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresoInicio.setText("Atras");
        btnregresoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, -1, -1));

        btnMenuRegistroAdmin.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuRegistroAdmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuRegistroAdmin.setText("Inicio");
        btnMenuRegistroAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistroAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuRegistroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 261, -1));

        btnMenuRegistroLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuRegistroLibro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuRegistroLibro.setText("Pedir Prestamo");
        btnMenuRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistroLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 261, -1));

        btnMenuCarnet.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuCarnet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuCarnet.setText("Visualizar Carnet");
        btnMenuCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCarnetActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 261, -1));

        btnMenuMulta.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuMulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuMulta.setText("Pagar multas");
        btnMenuMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 261, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnConsultarLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultarLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarLibro.setText("Consultar");
        btnConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarLibroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del libro:");

        NombreLibroPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        NombreLibroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreLibroPrestamoActionPerformed(evt);
            }
        });

        btnPrestamoLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnPrestamoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrestamoLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamoLibro.setText("Prestamo");
        btnPrestamoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoLibroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Prestamo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ejemplar del libro:");

        EjemplarLibroPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        EjemplarLibroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjemplarLibroPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreLibroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(btnConsultarLibro))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EjemplarLibroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreLibroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EjemplarLibroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresoInicioActionPerformed

    private void btnMenuRegistroAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistroAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegistroAdminActionPerformed

    private void btnMenuRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistroLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegistroLibroActionPerformed

    private void btnMenuCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuCarnetActionPerformed

    private void btnMenuMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuMultaActionPerformed

    private void btnConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarLibroActionPerformed

    private void NombreLibroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreLibroPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreLibroPrestamoActionPerformed

    private void btnPrestamoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamoLibroActionPerformed

    private void EjemplarLibroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjemplarLibroPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EjemplarLibroPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrestamoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField EjemplarLibroPrestamo;
    public javax.swing.JTextField NombreLibroPrestamo;
    public javax.swing.JButton btnConsultarLibro;
    public javax.swing.JButton btnMenuCarnet;
    public javax.swing.JButton btnMenuMulta;
    public javax.swing.JButton btnMenuRegistroAdmin;
    public javax.swing.JButton btnMenuRegistroLibro;
    public javax.swing.JButton btnPrestamoLibro;
    public javax.swing.JButton btnregresoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
