/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Luis
 */
public class VentanaClienteBuscarCarnet extends javax.swing.JFrame {

    /**
     * Creates new form Ventana12
     */
    public VentanaClienteBuscarCarnet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnregresoInicio = new javax.swing.JButton();
        btnMenuRegistroAdmin = new javax.swing.JButton();
        btnMenuRegistroLibro = new javax.swing.JButton();
        btnMenuCarnet = new javax.swing.JButton();
        btnMenuMulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdCarnet1 = new javax.swing.JTextField();
        btnBusquedaCarnet1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ClienteCarnet1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DeudasClientes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EstadoCarnet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnregresoInicio.setBackground(new java.awt.Color(0, 51, 51));
        btnregresoInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresoInicio.setText("Atras");
        btnregresoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, -1, -1));

        btnMenuRegistroAdmin.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuRegistroAdmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuRegistroAdmin.setText("Inicio");
        btnMenuRegistroAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistroAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuRegistroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 261, -1));

        btnMenuRegistroLibro.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuRegistroLibro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuRegistroLibro.setText("Pedir Prestamo");
        btnMenuRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistroLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuRegistroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 261, -1));

        btnMenuCarnet.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuCarnet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuCarnet.setText("Visualizar Carnet");
        btnMenuCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCarnetActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 261, -1));

        btnMenuMulta.setBackground(new java.awt.Color(0, 102, 102));
        btnMenuMulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuMulta.setText("Pagar multas");
        btnMenuMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 261, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Buscar Carnet");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Id del Carnet:");

        IdCarnet1.setBackground(new java.awt.Color(255, 255, 255));

        btnBusquedaCarnet1.setBackground(new java.awt.Color(0, 102, 102));
        btnBusquedaCarnet1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBusquedaCarnet1.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaCarnet1.setText("Buscar");
        btnBusquedaCarnet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaCarnet1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del cliente:");

        ClienteCarnet1.setBackground(new java.awt.Color(255, 255, 255));
        ClienteCarnet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCarnet1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("¿Tiene deudas?");

        DeudasClientes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Estado del carnet");

        EstadoCarnet.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IdCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBusquedaCarnet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClienteCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DeudasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel5)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IdCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusquedaCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ClienteCarnet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeudasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(EstadoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 580, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaCarnet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaCarnet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaCarnet1ActionPerformed

    private void btnregresoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresoInicioActionPerformed

    private void btnMenuRegistroAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistroAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegistroAdminActionPerformed

    private void btnMenuRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistroLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuRegistroLibroActionPerformed

    private void btnMenuCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuCarnetActionPerformed

    private void btnMenuMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuMultaActionPerformed

    private void ClienteCarnet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteCarnet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteCarnet1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuscarCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuscarCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuscarCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuscarCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClienteBuscarCarnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ClienteCarnet1;
    public javax.swing.JTextField DeudasClientes;
    public javax.swing.JTextField EstadoCarnet;
    public javax.swing.JTextField IdCarnet1;
    public javax.swing.JButton btnBusquedaCarnet1;
    public javax.swing.JButton btnMenuCarnet;
    public javax.swing.JButton btnMenuMulta;
    public javax.swing.JButton btnMenuRegistroAdmin;
    public javax.swing.JButton btnMenuRegistroLibro;
    public javax.swing.JButton btnregresoInicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
